/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as venmoOtcMultisigSol from "./VenmoOTCMultisig.sol";
export type { venmoOtcMultisigSol };
export type { MockUSDT } from "./MockUSDT";
