/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface VenmoOTCMultisigInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createOrder"
      | "getOrder"
      | "nextOrderId"
      | "orders"
      | "signOrder"
      | "updateChoice"
      | "usdtToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChoiceUpdated"
      | "OrderCreated"
      | "OrderExecuted"
      | "OrderSigned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createOrder",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextOrderId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signOrder",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateChoice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdtToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextOrderId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "signOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateChoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdtToken", data: BytesLike): Result;
}

export namespace ChoiceUpdatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    signer: AddressLike,
    newChoice: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    signer: string,
    newChoice: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    signer: string;
    newChoice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    initiator: AddressLike,
    counterparty: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    initiator: string,
    counterparty: string,
    amount: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    initiator: string;
    counterparty: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderExecutedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderSignedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    signer: AddressLike,
    choice: BigNumberish
  ];
  export type OutputTuple = [orderId: bigint, signer: string, choice: bigint];
  export interface OutputObject {
    orderId: bigint;
    signer: string;
    choice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VenmoOTCMultisig extends BaseContract {
  connect(runner?: ContractRunner | null): VenmoOTCMultisig;
  waitForDeployment(): Promise<this>;

  interface: VenmoOTCMultisigInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createOrder: TypedContractMethod<
    [_counterparty: AddressLike, _amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getOrder: TypedContractMethod<
    [_orderId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        initiator: string;
        counterparty: string;
        amount: bigint;
        initiatorChoice: bigint;
        counterpartyChoice: bigint;
        status: bigint;
        initiatorSigned: boolean;
        counterpartySigned: boolean;
      }
    ],
    "view"
  >;

  nextOrderId: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        initiator: string;
        counterparty: string;
        amount: bigint;
        initiatorChoice: bigint;
        counterpartyChoice: bigint;
        status: bigint;
        initiatorSigned: boolean;
        counterpartySigned: boolean;
      }
    ],
    "view"
  >;

  signOrder: TypedContractMethod<
    [_orderId: BigNumberish, _choice: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateChoice: TypedContractMethod<
    [_orderId: BigNumberish, _newChoice: BigNumberish],
    [void],
    "nonpayable"
  >;

  usdtToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createOrder"
  ): TypedContractMethod<
    [_counterparty: AddressLike, _amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [_orderId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        initiator: string;
        counterparty: string;
        amount: bigint;
        initiatorChoice: bigint;
        counterpartyChoice: bigint;
        status: bigint;
        initiatorSigned: boolean;
        counterpartySigned: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextOrderId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        initiator: string;
        counterparty: string;
        amount: bigint;
        initiatorChoice: bigint;
        counterpartyChoice: bigint;
        status: bigint;
        initiatorSigned: boolean;
        counterpartySigned: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "signOrder"
  ): TypedContractMethod<
    [_orderId: BigNumberish, _choice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateChoice"
  ): TypedContractMethod<
    [_orderId: BigNumberish, _newChoice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdtToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ChoiceUpdated"
  ): TypedContractEvent<
    ChoiceUpdatedEvent.InputTuple,
    ChoiceUpdatedEvent.OutputTuple,
    ChoiceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderExecuted"
  ): TypedContractEvent<
    OrderExecutedEvent.InputTuple,
    OrderExecutedEvent.OutputTuple,
    OrderExecutedEvent.OutputObject
  >;
  getEvent(
    key: "OrderSigned"
  ): TypedContractEvent<
    OrderSignedEvent.InputTuple,
    OrderSignedEvent.OutputTuple,
    OrderSignedEvent.OutputObject
  >;

  filters: {
    "ChoiceUpdated(uint256,address,uint8)": TypedContractEvent<
      ChoiceUpdatedEvent.InputTuple,
      ChoiceUpdatedEvent.OutputTuple,
      ChoiceUpdatedEvent.OutputObject
    >;
    ChoiceUpdated: TypedContractEvent<
      ChoiceUpdatedEvent.InputTuple,
      ChoiceUpdatedEvent.OutputTuple,
      ChoiceUpdatedEvent.OutputObject
    >;

    "OrderCreated(uint256,address,address,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderExecuted(uint256,address,uint256)": TypedContractEvent<
      OrderExecutedEvent.InputTuple,
      OrderExecutedEvent.OutputTuple,
      OrderExecutedEvent.OutputObject
    >;
    OrderExecuted: TypedContractEvent<
      OrderExecutedEvent.InputTuple,
      OrderExecutedEvent.OutputTuple,
      OrderExecutedEvent.OutputObject
    >;

    "OrderSigned(uint256,address,uint8)": TypedContractEvent<
      OrderSignedEvent.InputTuple,
      OrderSignedEvent.OutputTuple,
      OrderSignedEvent.OutputObject
    >;
    OrderSigned: TypedContractEvent<
      OrderSignedEvent.InputTuple,
      OrderSignedEvent.OutputTuple,
      OrderSignedEvent.OutputObject
    >;
  };
}
